In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.model_selection import cross_validate
from sklearn.naive_bayes import GaussianNB # ガウシアン

In [2]:
train_df = pd.read_csv("./C01_train_encoded.csv")
#train_df.info()

In [3]:
train_df.head(10)

id  project_is_approved  project_grade_category_enc_0  \
0  p036502                  1.0                             1   
1  p039565                  0.0                             0   
2  p233823                  1.0                             0   
3  p185307                  0.0                             0   
4  p013780                  1.0                             0   
5  p063374                  1.0                             1   
6  p103285                  1.0                             1   
7  p181781                  1.0                             1   
8  p114989                  1.0                             0   
9  p191410                  1.0                             1   

   project_grade_category_enc_1  project_grade_category_enc_2  \
0                             0                             0   
1                             1                             0   
2                             1                             0   
3                             1                             0   
4                             0                             1   
5                             0                             0   
6                             0                             0   
7                             0                             0   
8                             0                             1   
9                             0                             0   

   project_grade_category_enc_3  school_state_enc_0  school_state_enc_1  \
0                             0                   1                   0   
1                             0                   0                   1   
2                             0                   0                   0   
3                             0                   0                   0   
4                             0                   0                   0   
5                             0                   0                   0   
6                             0                   0                   0   
7                             0                   0                   0   
8                             0                   0                   0   
9                             0                   0                   0   

   school_state_enc_2  school_state_enc_3     ...       \
0                   0                   0     ...        
1                   0                   0     ...        
2                   1                   0     ...        
3                   0                   1     ...        
4                   0                   0     ...        
5                   0                   0     ...        
6                   0                   0     ...        
7                   0                   0     ...        
8                   0                   0     ...        
9                   0                   0     ...        

   project_essay_2_enc_534  project_essay_2_enc_535  project_essay_2_enc_536  \
0                        0                        0                        6   
1                        0                        0                        0   
2                        0                        1                        0   
3                        0                        0                        0   
4                        0                        0                        0   
5                        0                        0                        0   
6                        0                        0                        0   
7                        0                        0                        0   
8                        1                        0                        0   
9                        0                        0                        0   

   project_essay_2_enc_537  project_essay_2_enc_538  project_essay_2_enc_539  \
0                        0                        0                        0   
1                        0                        0                   

In [4]:
train_data = train_df.values
xs = train_data[:, 181:1208]  # project_title, project_essay1
y = train_data[:, 1]  # 正解データ列のみ抽出

In [5]:
xs.shape

(182080, 1027)

In [6]:
y.shape

(182080,)

In [7]:
train_X = xs[:150000, :]
train_Y = y[:150000]

test_X = xs[150000:, :]
test_Y = y[150000:]

In [8]:
train_Y[0:20].astype(int)

array([1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0])

In [14]:
train_Y[train_Y[0,] == 1].sum() / train_Y.size

0.84754

In [12]:
from sklearn.metrics import accuracy_score
clf = GaussianNB() # 正規分布を仮定したベイズ分類

# NG acc=0.84 全て1と判定
#from sklearn.naive_bayes import MultinomialNB
#clf = MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

clf.fit(train_X, train_Y.astype(int)) # 学習をする

pred_Y = clf.predict(test_X)
accuracy = accuracy_score(test_Y.astype(int), pred_Y)
print("acc = {:.2f}".format(accuracy))

acc = 0.55


In [24]:
pred_proba_Y = clf.predict_log_proba(test_X)
pred_proba_Y[100:300]

array([[-1340.15399745,     0.        ],
       [-1316.03834449,     0.        ],
       [-1328.76929715,     0.        ],
       [-1335.97164662,     0.        ],
       [-1334.36049467,     0.        ],
       [-1326.95867229,     0.        ],
       [-1332.47992899,     0.        ],
       [-1344.08772714,     0.        ],
       [-1339.63942898,     0.        ],
       [-1298.41265674,     0.        ],
       [-1303.30044246,     0.        ],
       [-1356.07797633,     0.        ],
       [-1350.96241067,     0.        ],
       [-1355.61550686,     0.        ],
       [-1323.10596821,     0.        ],
       [-1253.59957914,     0.        ],
       [-1336.01921654,     0.        ],
       [-2184.43104407,     0.        ],
       [-1338.25930053,     0.        ],
       [-1346.94858369,     0.        ],
       [-1338.79431796,     0.        ],
       [-1353.92537479,     0.        ],
       [-1339.48474924,     0.        ],
       [-1381.43381024,     0.        ],
       [-1352.63

In [13]:
pred_Y = clf.predict(train_X)

accuracy = accuracy_score(train_Y.astype(int), pred_Y)
print("acc = {:.2f}".format(accuracy))

acc = 0.55


In [16]:
pred_Y[0:20].astype(int)

array([0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1])

In [19]:
pred_Y[pred_Y == 1].sum() / pred_Y.size

0.48211333333333334

In [ ]:
test_df = pd.read_csv("./C01_test_encoded.csv")
#test_df.info()

In [ ]:
test_df.head(5)

In [ ]:
test_data = test_df.values
xs_test = test_data[:, 181:1208]

In [ ]:
y_test = clf.predict(xs_test)

In [ ]:
y_test.shape

In [ ]:
y_test[0:20]

In [ ]:
Submission = pd.DataFrame()
Submission["id"] = test_df["id"].astype(str)
Submission["project_is_approved"] = y_test.astype(str)

In [ ]:
import csv
Submission.to_csv("D04_Submission_7.csv", quoting=csv.QUOTE_NONNUMERIC , quotechar='"', index=False)