In [ ]:
from numpy import argmax
# define input string
data = 'hello world'
print(data)
# define universe of possible input values
alphabet = 'abcdefghijklmnopqrstuvwxyz '
# define a mapping of chars to integers
char_to_int = dict((c, i) for i, c in enumerate(alphabet))
int_to_char = dict((i, c) for i, c in enumerate(alphabet))
# integer encode input data
integer_encoded = [char_to_int[char] for char in data]
print(integer_encoded)
# one hot encode
onehot_encoded = list()
for value in integer_encoded:
	letter = [0 for _ in range(len(alphabet))]
	letter[value] = 1
	onehot_encoded.append(letter)
print(onehot_encoded)
# invert encoding
inverted = int_to_char[argmax(onehot_encoded[0])]
print(inverted)

In [ ]:
from numpy import argmax
import numpy as np
import pandas as pd

data = pd.Series(["apple","amazon","google","facebook","microsoft","apple","apple","amazon","amazon","google", None])
print(data)

In [ ]:
unique_data = pd.unique(data)
print(unique_data)

In [ ]:
char_to_int = dict((c, i) for i, c in enumerate(unique_data))
char_to_int

In [ ]:
int_to_char = dict((i, c) for i, c in enumerate(unique_data))
int_to_char

In [ ]:
#label encoding
label_encoded = [char_to_int[char] for char in data]
print(label_encoded)

In [ ]:
#one-hot encoding
integer_encoded = [char_to_int[char] for char in data]
onehot_encoded = list()
for value in integer_encoded:
	letter = [0 for _ in range(len(unique_data))]
	letter[value] = 1
	onehot_encoded.append(letter)
print(onehot_encoded)

In [ ]:
#binary encoding
integer_encoded = [char_to_int[char] for char in data]
binary_encoding = map(lambda x: list("{0:b}".format(x).zfill(10+1)), integer_encoded)
print(list(binary_encoding))

In [ ]:
import sys
sys.path

--実行モジュール.py or .ipynb
--my_modules(パッケージ)
  --init.py(パッケージを再帰的に読み込むためのダミーファイル)
  --my_module.py(module)
    --my_class(class)
      --my_def(function)

1.パッケージはimportできない 
import my_modules
->error

2.moduleはimportできる fromを使用してもよい 
import my_modules.my_module
-> ok

from my_modules import my_module
-> ok

3.classはimportできるが、fromを使用しないといけない(.でパスを指定できない)
import my_modules.my_module.myclass
-> error

from my_modules.my_module import myclass
-> ok



In [ ]:
import numpy as np
import pandas as pd
from my_modules.my_encoder import CategoryValueEncoder as CVE

data = pd.Series(["apple","amazon","google","facebook","microsoft","apple","apple","amazon","amazon","google", None])
encoder = CVE(data)
encoded = encoder.to_one_hot_encoding()
print(encoded)

In [ ]:
import numpy as np
import pandas as pd
import my_modules.my_encoder as my_encoder

data = pd.Series(["apple","amazon","google","facebook","microsoft","apple","apple","amazon","amazon","google", None])
encoder = my_encoder.CategoryValueEncoder(data)
encoded = encoder.to_binary_encoding()
print(encoded)

In [ ]:
import numpy as np
import pandas as pd
from my_modules import my_encoder

data = pd.Series(["apple","amazon","google","facebook","microsoft","apple","apple","amazon","amazon","google", None])
encoder = my_encoder.CategoryValueEncoder(data)
encoded = encoder.to_binary_encoding()
print(encoded)

In [ ]:
import numpy as np
import pandas as pd
from my_modules import my_encoder

data = pd.Series(["apple","amazon","google","facebook","microsoft","apple","apple","amazon","amazon","google", None], name = 'company_name')
encoder = my_encoder.CategoryValueEncoder(data)
encoded = encoder.to_binary_encoding()
print(encoded)

In [ ]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

fluits = ["apple & banana apple","maron","melon","grape & apple","lemon","melon & maron","orange","queie","orange"]
data = pd.Series(fluits, name = 'fruits_name')

series_name = 'fruits_name'

vectorizer = CountVectorizer()

corpus = data.values

#print(data.values)

series = vectorizer.fit_transform(corpus)
feature_name = vectorizer.get_feature_names()
print(feature_name)
print(series.toarray())
print(type(series))
print(type(series.toarray()))
print(type(list(series)))

dataframe = pd.DataFrame(series.toarray())
dataframe = dataframe.rename(lambda x: series_name + '_enc_' + str(x), axis='columns')
dataframe

In [ ]:
import pandas as pd
df = pd.DataFrame([[1,2,3,4,5,6],
                       [6,5,4,3,2,1],
                       [100,1,2,3,4,5],
                       [5,4,3,2,1,0]], columns=[*"ABCDEF"])

In [ ]:
df_x = df['A']
df_x

In [ ]:
mean = df_x.mean()
mean

In [ ]:
std = df_x.std(ddof=0)
std

In [ ]:
#norm = df_x.map(lambda x: round((x - mean) / std)).astype(int)
norm = df_x.map(lambda x: round((x - mean) / std / 10 + 0.5 , 2)).astype(float)
norm

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.model_selection import cross_validate
from xgboost import XGBClassifier
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
import seaborn as sns

In [ ]:
train_df = pd.read_csv("./Data/train.csv")
train_df.info()

In [ ]:
from my_modules.my_encoder import TextValueEncoder as TVE
df = TVE(train_df['project_subject_subcategories'])
df.to_bow_encoding()
vec = df.vectorizer
names = vec.get_feature_names()

In [ ]:
names

In [ ]:
cnt = len(names)
cnt

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                   index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                   index=[4, 5, 6, 7])

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                    'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'],
                    'D': ['D8', 'D9', 'D10', 'D11']},
                   index=[8, 9, 10, 11])

df4 = pd.DataFrame({'B': ['B2', 'B3', 'B6', 'B7'],
                    'D': ['D2', 'D3', 'D6', 'D7'],
                    'F': ['F2', 'F3', 'F6', 'F7']},
                   index=[2, 3, 6, 7])

In [ ]:
df1

In [ ]:
df2

In [ ]:
df3

In [ ]:
df4

In [ ]:
condat1 = pd.concat([df1, df4], axis=1)
condat1

In [ ]:
condat2 = pd.concat([df1, df4], axis=1, join_axes=[df1.index])
condat2

In [ ]:
import pandas as pd
stack = pd.DataFrame({'id': ['A01', 'A01', 'A02', 'A03'],
                     'description': ['apple', 'amazon', 'google', 'facebook'],
#                     'description': ['1', '2', '3', '4'],
                     'quantity': ['3', '2', '4', '10'],
                     'price': ['80', '100', '90', '70']})

In [ ]:
stack

In [ ]:
price = pd.Series(stack['quantity'].fillna(0.0).astype(int) * stack['price'].fillna(0.0).astype(int))
price = price.rename('total_price', axis='columns')
price

In [ ]:
stack = pd.concat([stack, price], axis=1)
stack

In [ ]:
grouped = stack.groupby('id')

In [ ]:
grouped.size()

In [ ]:
import functools

def f_reduce_sum(list):
    return functools.reduce(lambda x, y: x + y, list)

#ans = f_reduce_sum(range(1, 5))

In [ ]:
#ans

In [ ]:
def f_reduce_concat(list):
    return functools.reduce(lambda x, y: x + y, list)

#ans = f_reduce_concat(['abc','def','ghi'])

In [ ]:
#ans

In [ ]:
grouped.agg({'description': f_reduce_concat,
             'total_price': f_reduce_sum})

In [ ]:
import pandas as pd
left = pd.DataFrame({'id': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})

right = pd.DataFrame({'id': ['K1', 'K3', 'K5', 'K7'],
                      'C': ['C1', 'C3', 'C5', 'C7'],
                      'D': ['D1', 'D3', 'D5', 'D7']},
                     index=[1, 3, 5, 7])

In [ ]:
left

In [ ]:
right

In [ ]:
pd.merge(left, right, on='id', how='left')

In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.model_selection import cross_validate
from xgboost import XGBClassifier
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
import seaborn as sns

In [2]:
#train_df = pd.read_csv("./Data/train.csv")
train_df = pd.read_csv("./Data/test.csv")
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78035 entries, 0 to 78034
Data columns (total 15 columns):
id                                              78035 non-null object
teacher_id                                      78035 non-null object
teacher_prefix                                  78034 non-null object
school_state                                    78035 non-null object
project_submitted_datetime                      78035 non-null object
project_grade_category                          78035 non-null object
project_subject_categories                      78035 non-null object
project_subject_subcategories                   78035 non-null object
project_title                                   78035 non-null object
project_essay_1                                 78035 non-null object
project_essay_2                                 78035 non-null object
project_essay_3                                 2704 non-null object
project_essay_4                                 2704

/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3018: DtypeWarning: Columns (11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [9]:
import nltk
def noun_stem_analyzer(string):
    st = nltk.stem.lancaster.LancasterStemmer()
    return [st.stem(word) for word, pos in nltk.pos_tag(
            nltk.word_tokenize(string)) if pos in ["NNS", "VBP", "VB", "NNP", "JJ"]]

In [15]:
from my_modules.my_encoder import CategoryValueEncoder as CVE
from my_modules.my_encoder import TextValueEncoder as TVE
from my_modules.my_encoder import DateValueEncoder as DVE
from my_modules.my_encoder import NumericValueEncoder as NVE
from sklearn.feature_extraction.text import CountVectorizer

df1 = train_df['project_essay_1']
enc1 = TVE(df1[0:10000])
#enc1 = TVE(df1)
# 出現頻度が1%未満のデータは無視する。
# 理由：1回でた単語のデータのラベルが正であっても負であっても、その単語との因果関係を認められないから。
enc1.vectorizer = CountVectorizer(min_df=0.01, max_df=1.00, stop_words="english", analyzer=noun_stem_analyzer) # stop_words="english",
df2 = enc1.to_bow_encoding()
names = enc1.vectorizer.get_feature_names()

In [16]:
len(names)

399

In [17]:
names

["'m",
 "'re",
 "'ve",
 '21st',
 '\\',
 '\\r\\n',
 '\\r\\n\\r\\n',
 '\\r\\n\\r\\ni',
 '\\r\\n\\r\\nmy',
 '\\r\\n\\r\\nour',
 '\\r\\n\\r\\nthe',
 '\\r\\ni',
 '\\r\\nmy',
 '\\r\\nour',
 'abl',
 'academ',
 'accompl',
 'achiev',
 'act',
 'ad',
 'addit',
 'adult',
 'adv',
 'afford',
 'afr',
 'allow',
 'am',
 'amaz',
 'apply',
 'apprecy',
 'ar',
 'area',
 'art',
 'ask',
 'attend',
 'aut',
 'avail',
 'awesom',
 'background',
 'bas',
 'be',
 'beauty',
 'becom',
 'begin',
 'behavy',
 'believ',
 'benefit',
 'big',
 'bil',
 'book',
 'boy',
 'bright',
 'bring',
 'build',
 'busy',
 'cap',
 'car',
 'cent',
 'chair',
 'challeng',
 'chang',
 'childr',
 'cho',
 'choos',
 'circumst',
 'city',
 'class',
 'classroom',
 'clos',
 'collab',
 'com',
 'comfort',
 'common',
 'commun',
 'complet',
 'comput',
 'conceiv',
 'connect',
 'continu',
 'control',
 'country',
 'cre',
 'crit',
 'cult',
 'cur',
 'cury',
 'dai',
 'day',
 'deserv',
 'desk',
 'develop',
 'diff',
 'difficult',
 'dis',
 'discov',
 'discuss',
 '

In [ ]:
from my_modules.my_encoder import CategoryValueEncoder as CVE
from my_modules.my_encoder import TextValueEncoder as TVE
from my_modules.my_encoder import DateValueEncoder as DVE
from my_modules.my_encoder import NumericValueEncoder as NVE
from sklearn.feature_extraction.text import CountVectorizer

df1 = train_df['project_title']
#enc1 = TVE(df1[0:30000])
enc1 = TVE(df1)
# 出現頻度が1%未満のデータは無視する。
# 理由：1回でた単語のデータのラベルが正であっても負であっても、その単語との因果関係を認められないから。
enc1.vectorizer = CountVectorizer(min_df=0.01, max_df=1.00, stop_words="english") # We get ValueError when get any data. You should enhance range. 
df2 = enc1.to_bow_encoding()
names = enc1.vectorizer.get_feature_names()

In [ ]:
len(names)

In [ ]:
names

In [ ]:
import pandas as pd
train_df = pd.DataFrame({'id': ['A01', 'A01', 'A02', 'A03'],
                     'description': ['apple', 'amazon', 'google', 'facebook'],
                     'quantity': ['3', '2', '4', '10'],
                     'price': ['80', '100', '90', '70']})
train_df

In [ ]:
#カテゴリ変数の変換
hot_list = ['A02', 'A03']
train_df['quantity'] = train_df['id'].apply(lambda x: 1 if x in hot_list else 0)
#train_df['quantity'] = train_df['id'].map( {'A01': 0, 'A02': 1, 'A03': 2} ).astype(int)
train_df

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('tagsets')

In [7]:
string = "Most of my kindergarten students come from low"
words = nltk.word_tokenize(string)
words

['Most', 'of', 'my', 'kindergarten', 'students', 'come', 'from', 'low']

In [8]:
tags = nltk.pos_tag(words)
tags

[('Most', 'JJS'),
 ('of', 'IN'),
 ('my', 'PRP$'),
 ('kindergarten', 'JJ'),
 ('students', 'NNS'),
 ('come', 'VBP'),
 ('from', 'IN'),
 ('low', 'JJ')]

In [ ]:
anser = noun_stem_analyzer(string)
anser

In [ ]:
nltk.help.upenn_tagset()

In [5]:
import numpy as np
from sklearn.naive_bayes import GaussianNB # ガウシアン

X = np.array([[1,2,3,4,5,6,7,8],
              [1,1,3,4,5,6,6,7],
              [2,1,2,4,5,8,8,8]]) # 特徴ベクトル
y = np.array([1, 2, 3]) # そのラベル
t = np.array([[2,2,4,5,6,8,8,8],
              [2,2,4,5,6,0,0,0]]) # テストデータ

clf = GaussianNB() # 正規分布を仮定したベイズ分類
clf.fit(X, y) # 学習をする
clf.predict(t) # => [3]

array([3, 2])

In [6]:
from sklearn.naive_bayes import BernoulliNB
clf = BernoulliNB()
clf.fit(X, y)
clf.predict(t) #=> [1]

array([1, 1])

In [8]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)
clf.fit(X, y)
clf.predict(t) #=> [2]

array([2, 2])